Fix currency spaces
Djaler/evil-bot pull request #115
Opened 2020-11-02 16:12 UTC by InsanusMokrassar

2020-11-02 18:50 UTC, Djaler commented on src/main/kotlin/com/github/djaler/evilbot/handlers/CommandHandler.kt
> +val spacesRegex = Regex("\s*")
может `\s+`? А то пустоту сматчит тоже

2020-11-02 18:52 UTC, Djaler commented on src/main/kotlin/com/github/djaler/evilbot/handlers/CommandHandler.kt
> +val spacesRegex = Regex("\s*")
А, ну и экранировать слэш забыл

2020-11-02 18:53 UTC, Djaler requested changes
И нужно коммит по спецификации назвать https://www.conventionalcommits.org/
Можно на русском

2020-11-02 19:36 UTC, InsanusMokrassar commented on src/main/kotlin/com/github/djaler/evilbot/handlers/CommandHandler.kt
> +val spacesRegex = Regex("\s*")
Поправил

2020-11-02 19:36 UTC, InsanusMokrassar commented
> И нужно коммит по спецификации назвать https://www.conventionalcommits.org/
> Можно на русском

Поправил

2020-11-02 20:07 UTC, Djaler requested changes
Надо слить в один коммит. Ну и всё ещё не собирается

2020-11-03 04:53 UTC, InsanusMokrassar commented
> Надо слить в один коммит. Ну и всё ещё не собирается

Ок, разберусь

2020-11-03 06:16 UTC, Djaler commented
C маленькой буквы и в форме "исправлено ...", пожалуйста)

2020-11-07 07:50 UTC, merged