Added welcome message with gif animation
Djaler/evil-bot pull request #68
Opened 2020-08-03 23:00 UTC by tujh2

ha ha post ironic

2020-09-08 09:04 UTC, Djaler requested changes
Оставил замечания. И ещё - нужно над коммитами поработать. https://www.conventionalcommits.org/ru/v1.0.0-beta.4/
Сообщение можно и на русском.
По-хорошему - 2 коммита (в одном добавление кубика, во втором добавление гифки)

2020-09-08 09:04 UTC, Djaler commented on src/main/kotlin/com/github/djaler/evilbot/handlers/Captcha.kt
>              val captchaMessage = telegramClient.sendTextTo(
можно этим сообщением отвечать на сообщение с кубиком. Тогда не нужно будет передавать в callbackdata идентификатор сообщения с кубиком. А то я боюсь, что слишком большие данные получаются. А там 64 символа ограничение

2020-09-08 09:04 UTC, Djaler commented on src/main/kotlin/com/github/djaler/evilbot/handlers/Captcha.kt
> +        if (callbackData.cubeValue != callbackData.value) {
ещё не вижу смысла передавать в данных и значение кнопки и значение кубика. Можно в каждую кнопку передавать просто +/-, в зависимости от того, совпадает ли значение кнопки с кубиком или нет

2020-09-09 13:12 UTC, tujh2 commented on src/main/kotlin/com/github/djaler/evilbot/handlers/Captcha.kt
> +        if (callbackData.cubeValue != callbackData.value) {
Значение стоит передавать только для того, чтобы данные в кнопочках различались. Если мы передаем одинаковые данные, то при нажатии на любую неправильную кнопку начнут крутиться лоадеры у всех неправильных кнопок.

2020-09-09 13:16 UTC, tujh2 commented on src/main/kotlin/com/github/djaler/evilbot/handlers/Captcha.kt
> +            while (s.size < 6) {
Справедливо

2020-09-09 18:50 UTC, Djaler commented on src/main/kotlin/com/github/djaler/evilbot/handlers/Captcha.kt
> +        if (callbackData.cubeValue != callbackData.value) {
А, не знал о таком

2020-09-12 13:09 UTC, closed without merging